### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by crssi** [gbaptista/luminous#17]
Hi @gbaptista, can introduce an option to make text bigger?

Thank you

**Comment by gbaptista** [comment]
Hi @crssi! The texts really are very small! I'll see what I can do to improve this.

Thanks for the suggestion!

**Comment by gbaptista** [comment]
Hi @crssi, sorry for the long delay.

I've created an option to increase the texts, see: *UI Improvements #57*.

What do you think? Would that work for you?

**Comment by crssi** [comment]
Hey, thank you, but in version 0.0.15 the "zoom in" and "show code details" are not visible (at least not here, FF 58.0.2, x64, Win10).
Also, under settings when selected reports, the page loads indefinitely.

Cheers

**Comment by gbaptista** [comment]
Hi @crssi! It was not published yet at the time, it is now available in version `0.0.17`. Let me know if it's better this way!

About the Reports, what value is in your `indexedDB.enabled` setting at Firefox's `about: config`?

If `false`, this is probably why Reports do not work:
![selection_345](https://user-images.githubusercontent.com/29520/36236043-19033aa0-11db-11e8-9329-ad8538162c62.jpg)

**Comment by crssi** [comment]
My bad. It was not `indexedDB.enabled` problem, but I had for some reasons blocked access to `storage\temporary` folder.
Zoom is great now.

I have another issue, but will report in separate one.
