### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by SeppNel** [gbaptista/luminous#19]
Im not a very good designer, but i think this is an improvement.

![captura](https://user-images.githubusercontent.com/35899928/35761774-c0b82efc-088c-11e8-90a4-e4a8130a0085.PNG)

(The grey area in "ayuda" is because my mouse was there)

**Comment by gbaptista** [comment]
@SeppNel I liked the suggestions, I believe we can try some changes!

The bottom lines dividing the different codes (Web APIs, handleEvent, etc.) help in the visualization! I'm making some menu changes and trying out new UIs (see #25), they've changed a bit, but I'll soon try to apply your suggestions to see how they fit.

many thanks!

**Comment by SeppNel** [comment]
@gbaptista Wow! The new settings page looks very nice! Nice work!
You could try to add "padding-top: 0.5em;" on the ".form-check" class in the first tab.

And I have the code of the popup in my github if you want it.
