### ISSUE TITLE
disable code injection on openstreetmap

### ISSUE THREAD

**Issue by 2glops** [gbaptista/luminous#36]
Testing this interesting addon - FF58, don't know if this is an issue but I have to disable code injection on https://www.openstreetmap.org/
because "mousemove" is always persistent with code injection.

**Comment by gbaptista** [comment]
@2glops Thank you **so much** for reporting this behavior. Is definitely an issue.

This helped me discover a bug that was causing problems on many mainstream websites. I'm working on a fix and will release a new version as soon as possible.

More details at: "*Fix removeEventListener problem #37*"

Thanks again!

**Comment by gbaptista** [comment]
@2glops Version `0.0.11` is available at [*Firefox Add-ons*](https://addons.mozilla.org/en-US/firefox/addon/luminous/). Could you please try again and see if the problem has been solved? tks!

**Comment by 2glops** [comment]
Version 0.0.11 solved the issue !
Thanks
