### ISSUE TITLE
Version 0.0.13 not working

### ISSUE THREAD

**Issue by sleek22** [gbaptista/luminous#46]
I installed and have been using version 0.0.12 for a day and this add-on is amazing. It has the fine-grained control that other blockers are lacking.

But when I updated to version 0.0.13, I get nothing detected in the panel. I tried reinstalling but no change. Reverting back to version 0.0.12 and that still works.

I'm on Firefox version 59.0b8.

UPDATE***********

I found the problem. Seeing "Geolocation API support" and knowing that I have geolocation turned off (geo.enabled set to false in about:config), I turned it back on and the panel now shows detections. I tested it several times back and forth and that is what is causing the problem.

Being that geolocation being turned on is not a big problem, I can use the latest version. Just curious as to why it forces it to have to be on for it to work.

**Comment by GitCurious** [comment]
Issue exists here also - due to 'geo.enabled' pref.
(Waterfox 56.04)

**Comment by gbaptista** [comment]
@sleek22 Thank you very much for reporting the problem and going deep into the investigation to identify the reason. With that it was very easy to get right to the point and solve what was breaking!

@GitCurious Thank you too for pointing out that you also have the problem.

The correction has already been made (*Fix geolocation issue #47*) and I am preparing a new build.

**Comment by GitCurious** [comment]
Thankyou gbaptista....now working with v. 0.0.1.4

**Comment by sleek22** [comment]
Just installed version 0.0.015 and tested with geo.enabled set to false and it is working fine.

Thank you to the author for the quick fix.
