### ISSUE TITLE
UI usability suggestion

### ISSUE THREAD

**Issue by GitCurious** [gbaptista/luminous#54]
It may be useful (easier) to make any blocked item on the list a "global" block when the specific site checkbox is unchecked in the user interface popup.

**1. Uncheck the site checkbox**
![global](https://user-images.githubusercontent.com/18083484/36076639-cc8fe988-0f56-11e8-863d-d5b12fc3a33e.png)
**2. Block any item and it automatically becomes a "global" blocked item.**

Maybe I`m crazy - but this seems like it might be a useful option ?

**Comment by gbaptista** [comment]
@GitCurious I believe this can be very helpful!

Maybe creating this behavior based on the website checkbox can be a bit confusing.
I thought of a new option called "apply actions to default rules", see: *UI Improvements #57*

When this option is turned on, any action will be applied to the default rules. What do you think?

**Comment by GitCurious** [comment]
That`s even easier for users to understand :)
