### ISSUE TITLE
Could there be a way to log to the Web Console when actions are blocked/allowed?

### ISSUE THREAD

**Issue by jawz101** [gbaptista/luminous#59]
It's difficult to know which counter is being triggered unless I click one a bunch of times, go into the add-on window and see which item starts changing colors.  If I could have the developer console open and simply see what is happening on screen it would be more helpful.  Additionally, [uBlock added a feature to utilize the Firefox sidebar to keep their log screen open](https://github.com/gorhill/uBlock/issues/2854) which might be another way to possibly have the pop-up details remain open while browsing.

[Sidebar example for Opera](https://github.com/gorhill/uBlock/commit/295cf563ee809af144afea9c3ce94037a927eab3), fwiw

**Comment by gbaptista** [comment]
@jawz101 I believe it is possible and I think this can be very useful. In the last build I sort of left the code ready to start something like that (see [*js/content/readers/data.js#L83*](https://github.com/gbaptista/luminous/blob/0.0.17/js/content/readers/data.js#L83)).

I like the idea of a sidebar, I'll see the references. Thanks for the sugestion!

**Comment by gbaptista** [comment]
@jawz101 Doing some experiments: *[WIP] Logs #76*

**Comment by gbaptista** [comment]
@jawz101 Version `0.0.23` (see #80) is now available with log panels. Let me know if you have any questions or comments. Thank you again!

**Comment by jawz101** [comment]
wow.  This makes things so much more usable.  Thank you again for your work
