### ISSUE TITLE
0.0.17: Cannot login to github

### ISSUE THREAD

**Issue by crssi** [gbaptista/luminous#62]
Fresh install of 0.0.17 with nothing set to be blocked. Still I can't login to github.

Cheers

**Comment by gbaptista** [comment]
Hi @crssi, thank you for reporting the problem!

I identified the problem and made a correction: *Fix Stack and Cookies issues for Firefox #65*

In version `0.0.18` the problem should not happen any more.

Could you please try again?

**Comment by crssi** [comment]
Works now... thank you 😃 
Cheers
