### ISSUE TITLE
option to take notes

### ISSUE THREAD

**Issue by jawz101** [gbaptista/luminous#63]
This is silly but, with the amount of data returned, I was wondering if it would be possible to have a note field or maybe an additional option besides allowed and blocked.

Like, the default would be "allow"
"block" to block
"permit" is functionally the same as "allow" but is maybe blue in color and I can write a note such as "causes breakage when clicking on buttons" or whatever.  That way I won't go blocking it again without knowing why I allowed it in the first place.

**Comment by gbaptista** [comment]
Very interesting idea! We really have many options and it's hard to remember why we blocked something or not. Some way of writing notes on this could help a lot. I'll try to figure out some way to do this.

Thanks for the sugestion!

**Comment by jawz101** [comment]
Thanks.  I was just thinking out loud and I am happy you are so receptive :)

**Comment by gbaptista** [comment]
@jawz101 Starting work on this, comments would be very useful in this PR:
- *[WIP] Take a Note Experiment #92*
