### ISSUE TITLE
[Wiki] What is detected?

### ISSUE THREAD

**Issue by Atavic** [gbaptista/luminous#84]
I saw some typo, like `hanleEvent` instead of `handleEvent`

Here's a revision: https://gist.github.com/Atavic/e17e1a93bd82cc891daa9537e43a8aa1

**Comment by gbaptista** [comment]
@Atavic Thank you for reporting the typos, I've also seen your comment [here](https://github.com/gbaptista/luminous/commit/0c730ea738e156b5a449e441a711caea53a78849#commitcomment-28002673). In fact these documents are not on the wiki, they are in the source code so everyone can change them in the fork and make a pull request.

For example, all the guides can be changed here: https://github.com/gbaptista/luminous/tree/master/doc/en-US/guides

This specific page (*What is detected?*) can be changed directly here: https://github.com/gbaptista/luminous/blob/master/doc/en-US/guides/how-it-works/what-is-detected.md

Let me know if you need any help or have any questions about this. If for some reason you can not make the changes, do not worry, I'll make the corrections here soon.

**Comment by Atavic** [comment]
Thank you for the clarifications, will use my fork from now onwards.
